inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - config/**/*
    - bin/*
    - db/**/*
    - Gemfile
    - vendor/bundle/**/*
    - node_modules/**/*
    - tmp/**/*
Layout/LineLength:
  Max: 140
Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context
    - state_machine
    - factory
    - define # FactoryBot.define
Style/Documentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/RescueStandardError:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

