# TODO: add all players which changed club at Serie A
club_transfers:
  Kurtic:
    from: SPA
    to: PAR
  Perin:
    from: JUV
    to: GEN
  Destro:
    from: BOL
    to: GEN
  Caldara:
    from: MIL
    to: ATA
  Kjaer:
    from: ATA
    to: MIL
  Dabo:
    from: FIO
    to: SPA
