# For players exchange between teams, create records like this:
#exchanges:
#  -
#    from:
#      name: western_boog
#      players:
#        - Izzo
#    to:
#      name: original_gangster
#      players:
#        - Berardi
