# TODO: add all players which leave Serie A
# TODO: add all players which team managers decide retired
free_agents:
  banderstadt:
    - Castro
    - Rogerio
    - Balotelli
    - Lasagna
    - Zaccagni
  fenice_rossa:
    - Zappacosta
    - Lerager
    - Elmas
  nemesis:
    - Bernardeschi
    - Samir
    - Krunic
    - Pinamonti
  original_gangster:
    - Reina
    - Mandzukic
    - Morosini
    - Llorente
    - Kouame
    - Bonaventura
    - Consigli
    - Mkhitaryan
  pratima:
    - Murillo
    - Berni
    - Zaniolo
    - Ghoulam
  semper_fidelis:
    - Pussetto
    - Ranocchia
    - Duarte
    - Boateng
    - Zmrhal
    - Dessena
  sx:
    - Henderson
    - Radu
    - Iago
    - Shakhov
    - Badelj
    - Sanchez
  tori_granato:
    - Benzar
#    - Rodriguez
  vittoria:
  western_boog:
    - Nestorovski
    - Pavoletti
    - Lozano
