players:
  Donnarumma G:
    - position:
      - Por
    - club: MIL
  Audero:
    - position:
      - Por
    - club: SAM
  Acerbi:
    - position:
      - Dc
    - club: LAZ
  Mancini G:
    - position:
      - Dc
    - club: ROM
  Palomino:
    - position:
      - Dc
    - club: ATA
  Gagliolo:
    - position:
      - Dc
      - Ds
    - club: PAR
  Criscito:
    - position:
      - Dc
      - Ds
      - E
    - club: GEN
  Biraghi:
    - position:
      - Ds
      - E
    - club: INT
  Danilo:
    - position:
      - Ds
      - Dd
      - E
    - club: JUV
  Lirola:
    - position:
      - Dd
      - E
    - club: FIO
  Lazzari M:
    - position:
      - E
    - club: LAZ
  Nandez:
    - position:
      - M
      - C
    - club: CAG
  Obiang:
    - position:
      - M
      - C
    - club: SAS
  Rabiot:
    - position:
      - C
    - club: JUV
  Veretout:
    - position:
      - C
    - club: ROM
  Cristante:
    - position:
      - C
    - club: ROM
  Baselli:
    - position:
      - C
      - T
    - club: TOR
  Castro:
    - position:
      - C
      - T
    - club: CAG
  Kurtic:
    - position:
      - C
      - T
    - club: SPA
  Douglas Costa:
    - position:
      - W
    - club: JUV
  Chiesa:
    - position:
      - W
      - A
    - club: FIO
  Verdi:
    - position:
      - W
      - A
    - club: TOR
  Ilicic:
    - position:
      - A
    - club: ATA
  Inglese:
    - position:
      - Pc
    - club: PAR
  Zapata D:
    - position:
      - Pc
    - club: ATA
