players:
  Strakosha:
    - position:
      - Por
    - club: LAZ
  Ospina:
    - position:
      - Por
    - club: NAP
  De Ligt:
    - position:
      - Dc
    - club: JUV
  Bonifazi:
    - position:
      - Dc
    - club: TOR
  Muldur:
    - position:
      - Dc
      - Dd
    - club: SAS
  Asamoah:
    - position:
      - Ds
      - E
    - club: INT
  Pellegrini Lu:
    - position:
      - Ds
      - E
    - club: CAG
  Hysaj:
    - position:
      - Ds
      - Dd
      - E
    - club: NAP
  Zappacosta:
    - position:
      - Dd
      - E
    - club: ROM
  Gosens:
    - position:
      - E
    - club: ATA
  Medel:
    - position:
      - M
    - club: BOL
  Matuidi:
    - position:
      - M
      - C
    - club: JUV
  Lerager:
    - position:
      - M
      - C
    - club: GEN
  Elmas:
    - position:
      - C
      - T
    - club: NAP
  Pasalic:
    - position:
      - C
      - T
    - club: ATA
  Ruiz:
    - position:
      - C
      - T
    - club: NAP
  Cuadrado:
    - position:
      - E
      - W
    - club: JUV
  Orsolini:
    - position:
      - W
      - A
    - club: BOL
  Castillejo:
    - position:
      - W
      - A
    - club: MIL
  Dybala:
    - position:
      - A
    - club: JUV
  Sansone N:
    - position:
      - A
    - club: BOL
  Destro:
    - position:
      - Pc
    - club: BOL
  Zaza:
    - position:
      - Pc
    - club: TOR
  Milik:
    - position:
      - Pc
    - club: NAP
  Llorente:
    - position:
      - Pc
    - club: NAP
