players:
  Sirigu:
    - position:
      - Por
    - club: TOR
  Sepe:
    - position:
      - Por
    - club: PAR
  Bruno Alves:
    - position:
      - Dc
    - club: PAR
  Pezzella Ger:
    - position:
      - Dc
    - club: FIO
  Samir:
    - position:
      - Dc
      - Ds
    - club: UDI
  Igor:
    - position:
      - Dc
      - Ds
    - club: SPA
  Rrahmani:
    - position:
      - Dc
      - Ds
      - Dd
    - club: VER
  Tomiyasu:
    - position:
      - Dc
      - Dd
    - club: BOL
  Calabria:
    - position:
      - Dd
      - E
    - club: MIL
  Florenzi:
    - position:
      - Dd
      - E
    - club: ROM
  Allan:
    - position:
      - M
      - C
    - club: NAP
  Miguel Veloso:
    - position:
      - M
      - C
    - club: VER
  Bisoli:
    - position:
      - M
      - C
    - club: BRE
  Diawara:
    - position:
      - M
      - C
    - club: ROM
  Kessie:
    - position:
      - C
    - club: MIL
  Pjanic:
    - position:
      - C
    - club: JUV
  Pellegrini Lo:
    - position:
      - C
      - T
    - club: ROM
  Krunic:
    - position:
      - C
      - T
    - club: MIL
  Bernardeschi:
    - position:
      - W
      - A
    - club: JUV
  Suso:
    - position:
      - W
      - A
    - club: MIL
  Under:
    - position:
      - W
      - A
    - club: ROM
  Gomez A:
    - position:
      - T
      - A
    - club: ATA
  Joao Pedro:
    - position:
      - A
    - club: CAG
  Pinamonti:
    - position:
      - Pc
    - club: GEN
  Immobile:
    - position:
      - Pc
    - club: LAZ
