players:
  Consigli:
    - position:
      - Por
    - club: SAS
  Silvestri:
    - position:
      - Por
    - club: VER
  Reina:
    - position:
      - Por
    - club: MIL
  Ferrari G:
    - position:
      - Dc
    - club: SAS
  Marlon:
    - position:
      - Dc
    - club: SAS
  Peluso:
    - position:
      - Dc
      - Ds
    - club: SAS
  Bocchetti:
    - position:
      - Dc
      - Ds
    - club: VER
  Calderoni:
    - position:
      - Ds
      - E
    - club: LEC
  Rogerio:
    - position:
      - Ds
      - E
    - club: SAS
  Toljan:
    - position:
      - Ds
      - Dd
      - E
    - club: SAS
  De Silvestri:
    - position:
      - Dd
      - E
    - club: TOR
  Tonali:
    - position:
      - M
      - C
    - club: BRE
  Mandragora:
    - position:
      - M
      - C
    - club: UDI
  Meite:
    - position:
      - M
      - C
    - club: TOR
  Brozovic:
    - position:
      - C
    - club: INT
  Zaccagni:
    - position:
      - C
      - T
    - club: VER
  Berenguer:
    - position:
      - W
    - club: TOR
  Callejon:
    - position:
      - W
    - club: NAP
  Calhanoglu:
    - position:
      - T
    - club: MIL
  Morosini:
    - position:
      - T
      - A
    - club: BRE
  Falco:
    - position:
      - A
    - club: LEC
  Berardi:
    - position:
      - A
    - club: SAS
  Donnarumma Al:
    - position:
      - Pc
    - club: BRE
  Mandzukic:
    - position:
      - Pc
    - club: JUV
  Cristiano Ronaldo:
    - position:
      - Pc
    - club: JUV
