players:
  Handanovic:
    - position:
      - Por
    - club: INT
  Berni:
    - position:
      - Por
    - club: INT
  Padelli:
    - position:
      - Por
    - club: INT
  Romero C:
    - position:
      - Dc
    - club: GEN
  Colley:
    - position:
      - Dc
    - club: SAM
  Murillo:
    - position:
      - Dc
    - club: SAM
  Rodrigo Becao:
    - position:
      - Dc
    - club: UDI
  Masiello A:
    - position:
      - Dc
      - Dd
    - club: ATA
  Ghoulam:
    - position:
      - Ds
      - E
    - club: NAP
  Kolarov:
    - position:
      - Ds
      - E
    - club: ROM
  De Sciglio:
    - position:
      - Ds
      - Dd
      - E
    - club: JUV
  Ghiglione:
    - position:
      - Dd
      - E
    - club: GEN
  Parolo:
    - position:
      - M
      - C
    - club: LAZ
  Vecino:
    - position:
      - M
      - C
    - club: INT
  Sensi:
    - position:
      - C
    - club: INT
  Kulusevski:
    - position:
      - C
      - T
    - club: PAR
  Paqueta:
    - position:
      - T
    - club: MIL
  Zaniolo:
    - position:
      - T
    - club: ROM
  Soriano:
    - position:
      - T
    - club: BOL
  Candreva:
    - position:
      - E
      - W
    - club: INT
  Di Francesco F:
    - position:
      - W
    - club: SPA
  Boga:
    - position:
      - W
      - A
    - club: SAS
  Politano:
    - position:
      - W
      - A
    - club: INT
  Petagna:
    - position:
      - Pc
    - club: SPA
  Piatek:
    - position:
      - Pc
    - club: MIL
