players:
  Meret:
    - position:
      - Por
    - club: NAP
  Musso:
    - position:
      - Por
    - club: UDI
  Skriniar:
    - position:
      - Dc
    - club: INT
  Godin:
    - position:
      - Dc
    - club: INT
  Ranocchia:
    - position:
      - Dc
    - club: INT
  Duarte:
    - position:
      - Dc
    - club: MIL
  Musacchio:
    - position:
      - Dc
    - club: MIL
  Smalling:
    - position:
      - Dc
    - club: ROM
  Kjaer:
    - position:
      - Dc
    - club: ATA
  Di Lorenzo:
    - position:
      - Dd
      - E
    - club: NAP
  Ansaldi:
    - position:
      - E
    - club: TOR
  Dessena:
    - position:
      - E
      - M
    - club: BRE
  Amrabat:
    - position:
      - E
      - M
    - club: VER
  Ekdal:
    - position:
      - M
      - C
    - club: SAM
  Pulgar:
    - position:
      - M
      - C
    - club: FIO
  Schone:
    - position:
      - C
    - club: GEN
  Nainggolan:
    - position:
      - C
      - T
    - club: CAG
  Bonaventura:
    - position:
      - C
      - W
      - T
    - club: MIL
  Zmrhal:
    - position:
      - C
      - W
    - club: BRE
  Kluivert:
    - position:
      - W
    - club: ROM
  Pussetto:
    - position:
      - W
      - A
    - club: UDI
  Balotelli:
    - position:
      - Pc
    - club: BRE
  Lasagna:
    - position:
      - Pc
    - club: UDI
  Dzeko:
    - position:
      - Pc
    - club: ROM
  Higuain:
    - position:
      - Pc
    - club: JUV
