players:
  Donnaruma:
    - position:
      - Por
    - club: MIL
  Reina:
    - position:
      - Por
    - club: MIL
  Koulibaly:
    - position:
      - Dc
    - club: NAP
  Ferrari:
    - position:
      - Dc
    - club: SAS
  Andersen:
    - position:
      - Dc
    - club: SAM
  Caceres:
    - position:
      - Dc
      - Dd
    - club: JUV
  Crisito:
    - position:
      - Dc
      - Ds
    - club: GEN
  Srna:
    - position:
      - Dd
      - E
    - club: CAG
  Calabria:
    - position:
      - Dd
      - E
    - club: MIL
  Dalbert:
    - position:
      - Ds
      - E
    - club: INT
  Asamoah:
    - position:
      - D
      - E
    - club: INT
  Malcuit:
    - position:
      - Dd
      - E
    - club: NAP
  De Roon:
    - position:
      - M
      - C
    - club: ATA
  Matuidi:
    - position:
      - M
      - C
    - club: JUV
  Pjanic:
    - position:
      - C
    - club: JUV
  Baselli:
    - position:
      - C
    - club: TOR
  Freuler:
    - position:
      - C
    - club: ATA
  Milinkovic-Savic:
    - position:
      - C
      - T
    - club: LAZ
  Calhanoglu:
    - position:
      - T
      - A
    - club: MIL
  Gomez:
    - position:
      - A
    - club: ATA
  Dybala:
    - position:
      - A
    - club: JUV
  Sanabria:
    - position:
      - Pc
    - club: GEN
  Cutrone:
    - position:
      - Pc
    - club: MIL
  Antenucci:
    - position:
      - Pc
    - club: SPA
  Babacar:
    - position:
      - Pc
    - club: SAS
