players:
  Gollini:
    - position:
      - Por
    - club: ATA
  Radu I:
    - position:
      - Por
    - club: GEN
  Dragowski:
    - position:
      - Por
    - club: FIO
  Koulibaly:
    - position:
      - Dc
    - club: NAP
  De Vrij:
    - position:
      - Dc
    - club: INT
  Bonucci:
    - position:
      - Dc
    - club: JUV
  Troost-Ekong:
    - position:
      - Dc
    - club: UDI
  Stryger Larsen:
    - position:
      - Dc
      - Dd
      - E
    - club: UDI
  Darmian:
    - position:
      - Ds
      - Dd
      - E
    - club: PAR
  Hateboer:
    - position:
      - E
    - club: ATA
  Romulo:
    - position:
      - E
      - M
    - club: BRE
  Shakhov:
    - position:
      - M
      - C
    - club: LEC
  Locatelli M:
    - position:
      - M
      - C
    - club: SAS
  Badelj:
    - position:
      - M
      - C
    - club: FIO
  Benassi:
    - position:
      - C
    - club: FIO
  Henderson L:
    - position:
      - C
    - club: VER
  Freuler:
    - position:
      - C
    - club: ATA
  Traore HJ:
    - position:
      - C
      - T
    - club: SAS
  Luis Alberto:
    - position:
      - T
    - club: LAZ
  De Paul:
    - position:
      - T
      - A
    - club: UDI
  Iago Falque:
    - position:
      - A
    - club: TOR
  Rebic:
    - position:
      - A
    - club: MIL
  Sanchez A:
    - position:
      - A
    - club: INT
  Martinez L:
    - position:
      - Pc
    - club: INT
  Lapadula:
    - position:
      - Pc
    - club: LEC
