players:
  Skorupski:
    - position:
      - Por
    - club: BOL
  Da Costa:
    - position:
      - Por
    - club: BOL
  Zapata C:
    - position:
      - Dc
    - club: GEN
  Nkoulou:
    - position:
      - Dc
    - club: TOR
  Fazio:
    - position:
      - Dc
    - club: ROM
  Ceppitelli:
    - position:
      - Dc
    - club: CAG
  Luiz Felipe:
    - position:
      - Dc
    - club: LAZ
  Radu:
    - position:
      - Dc
      - Ds
    - club: LAZ
  Dambrosio:
    - position:
      - Dc
      - Ds
      - Dd
    - club: INT
  Martella:
    - position:
      - Ds
      - E
    - club: BRE
  Rodriguez R:
    - position:
      - Ds
      - E
    - club: MIL
  Benzar:
    - position:
      - Dd
      - E
    - club: LEC
  Lulic:
    - position:
      - E
      - C
    - club: LAZ
  Rincon:
    - position:
      - M
    - club: TOR
  De Roon:
    - position:
      - M
      - C
    - club: ATA
  Barella:
    - position:
      - M
      - C
    - club: INT
  Dabo:
    - position:
      - M
      - C
    - club: FIO
  Bentancur:
    - position:
      - C
    - club: JUV
  Lazovic:
    - position:
      - E
      - W
    - club: VER
  Mkhitaryan:
    - position:
      - T
      - A
    - club: ROM
  Kouame:
    - position:
      - A
    - club: GEN
  Boateng:
    - position:
      - A
    - club: FIO
  Caputo:
    - position:
      - Pc
    - club: SAS
  Simeone:
    - position:
      - Pc
    - club: CAG
  Belotti:
    - position:
      - Pc
    - club: TOR
