players:
  Pau Lopez:
    - position:
      - Por
    - club: ROM
  Berisha E:
    - position:
      - Por
    - club: SPA
  Romagnoli A:
    - position:
      - Dc
    - club: MIL
  Caldara:
    - position:
      - Dc
    - club: MIL
  Toloi:
    - position:
      - Dc
    - club: ATA
  Klavan:
    - position:
      - Dc
    - club: CAG
  Iacoponi:
    - position:
      - Dc
      - Dd
    - club: PAR
  Sabelli:
    - position:
      - Dd
      - E
    - club: BRE
  Hernandez T:
    - position:
      - Ds
      - E
    - club: MIL
  Spinazzola:
    - position:
      - Ds
      - E
    - club: ROM
  Mbaye:
    - position:
      - Ds
      - Dd
      - E
    - club: BOL
  Lucas Leiva:
    - position:
      - M
      - C
    - club: LAZ
  Kucka:
    - position:
      - M
      - C
    - club: PAR
  Can:
    - position:
      - M
      - C
    - club: JUV
  Duncan:
    - position:
      - M
      - C
    - club: SAS
  Khedira:
    - position:
      - C
    - club: JUV
  Malinovskyi:
    - position:
      - C
      - T
    - club: ATA
  Ramsey:
    - position:
      - T
    - club: JUV
  Ribery:
    - position:
      - W
      - A
    - club: FIO
  Gervinho:
    - position:
      - A
    - club: PAR
  Correa:
    - position:
      - A
    - club: LAZ
  Caprari:
    - position:
      - A
    - club: SAM
  Quagliarella:
    - position:
      - Pc
    - club: SAM
  Okaka:
    - position:
      - Pc
    - club: UDI
  Lukaku R:
    - position:
      - Pc
    - club: INT
