players:
  Szczesny:
    - position:
      - Por
    - club: JUV
  Buffon:
    - position:
      - Por
    - club: JUV
  Perin:
    - position:
      - Por
    - club: JUV
  Chiellini:
    - position:
      - Dc
    - club: JUV
  Manolas:
    - position:
      - Dc
    - club: NAP
  Luperto:
    - position:
      - Dc
      - Ds
    - club: NAP
  Denswil:
    - position:
      - Dc
      - Ds
    - club: BOL
  Milenkovic:
    - position:
      - Dc
      - Dd
    - club: FIO
  Izzo:
    - position:
      - Dc
      - Dd
    - club: TOR
  Alex Sandro:
    - position:
      - Ds
      - E
    - club: JUV
  Fofana:
    - position:
      - M
      - C
    - club: UDI
  Vieira:
    - position:
      - M
      - C
    - club: SAM
  Bennacer:
    - position:
      - M
      - C
    - club: MIL
  Missiroli:
    - position:
      - M
      - C
    - club: SPA
  Poli:
    - position:
      - M
      - C
    - club: BOL
  Milinkovic-Savic:
    - position:
      - C
      - T
    - club: LAZ
  Zielinski:
    - position:
      - C
      - T
    - club: NAP
  Ramirez:
    - position:
      - T
    - club: SAM
  Lozano:
    - position:
      - A
    - club: NAP
  Insigne:
    - position:
      - A
    - club: NAP
  Mertens:
    - position:
      - Pc
    - club: NAP
  Rafael Leao:
    - position:
      - Pc
    - club: MIL
  Nestorovski:
    - position:
      - Pc
    - club: UDI
  Pavoletti:
    - position:
      - Pc
    - club: CAG
  Muriel:
    - position:
      - Pc
    - club: ATA
