---
openapi: 3.0.1
info:
  title: MantraFootball API V1
  version: v1
paths:
  "/api/tournaments/{tournament_id}/divisions":
    parameters:
    - name: tournament_id
      in: path
      description: Tournament id
      required: true
      schema:
        type: string
    - name: season_id
      in: query
      required: false
      description: Season id
      schema:
        type: string
    get:
      summary: list tournament divisions
      tags:
      - Divisions
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/division"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_not_found"
  "/api/leagues":
    get:
      summary: list leagues
      tags:
      - Leagues
      parameters:
      - name: filter
        in: query
        type: object
        required: false
        schema:
          type: object
          properties:
            season_id:
              type: integer
              example: '123'
            tournament_id:
              type: integer
              example: '123'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/league_base"
  "/api/leagues/{id}":
    parameters:
    - name: id
      in: path
      description: League id
      required: true
      schema:
        type: string
    get:
      summary: show league
      tags:
      - Leagues
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/league"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_not_found"
  "/api/leagues/{league_id}/results":
    parameters:
    - name: league_id
      in: path
      description: League id
      required: true
      schema:
        type: string
    get:
      summary: list league results
      tags:
      - Results
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/result"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_not_found"
  "/api/seasons":
    get:
      summary: list seasons
      tags:
      - Seasons
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/season"
  "/api/teams/{id}":
    parameters:
    - name: id
      in: path
      description: Team id
      required: true
      schema:
        type: string
    get:
      summary: show team
      tags:
      - Teams
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/team"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_not_found"
  "/api/tournaments":
    get:
      summary: list tournaments
      tags:
      - Tournaments
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/tournament"
servers:
- url: http://localhost:3333
- url: http://staging.mantrafootball.org
- url: https://mantrafootball.org
components:
  schemas:
    division:
      type: object
      properties:
        id:
          type: integer
          example: 123
        level:
          type: string
          example: A
        leagues:
          type: array
          items:
            "$ref": "#/components/schemas/league_base"
      required:
      - id
      - level
    error_not_found:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
                example: not_found
              message:
                type: string
                example: Resource not found
            required:
            - key
            - message
      required:
      - errors
    league:
      type: object
      properties:
        id:
          type: integer
          example: 123
        auction_type:
          type: string
          example: blind_bids
          description: 'Available values: blind_bids, live'
        cloning_status:
          type: string
          example: unclonable
          description: 'Available values: unclonable, cloneable'
        division:
          type: string
          example: A1
          nullable: true
        division_id:
          type: integer
          example: '123'
          nullable: true
        leader:
          type: string
          example: Rossoneri
          nullable: true
        leader_logo:
          type: string
          example: https://s3.amazonaws.com/teams/default.png
          nullable: true
        link:
          type: string
          example: "/leagues/link"
        mantra_format:
          type: boolean
          example: true
          description: true for Mantra, false for national and eurocup leagues
        max_avg_def_score:
          type: string
          example: '8.0'
        min_avg_def_score:
          type: string
          example: '7.0'
        name:
          type: string
          example: San Siro
        promotion:
          type: integer
          example: 2
        relegation:
          type: integer
          example: 3
        round:
          type: integer
          example: 13
        season_id:
          type: integer
          example: 123
        season_end_year:
          type: integer
          example: 2024
        season_start_year:
          type: integer
          example: 2023
        status:
          type: string
          example: integer
          description: 'Available values: initial, active, archived'
        teams_count:
          type: integer
          example: 8
        tournament_id:
          type: integer
          example: 321
        transfer_status:
          type: string
          example: closed
          description: 'Available values: closed, open'
      required:
      - id
      - name
    league_base:
      type: object
      properties:
        id:
          type: integer
          example: 123
        division:
          type: string
          example: A1
          nullable: true
        division_id:
          type: integer
          example: 123
          nullable: true
        link:
          type: string
          example: "/leagues/link"
        name:
          type: string
          example: San Siro
        season_id:
          type: integer
          example: 123
        status:
          type: string
          example: active
          description: 'Available values: initial, active, archived'
        tournament_id:
          type: integer
          example: 321
      required:
      - id
      - name
    result:
      type: object
      properties:
        id:
          type: integer
          example: 123
        best_lineup:
          type: string
          example: '99.5'
        draws:
          type: integer
          example: 3
        form:
          type: array
          items:
            type: string
            example: W
          example:
          - W
          - D
          - L
        goals_difference:
          type: integer
          example: 13
        history:
          type: array
          items:
            type: object
            properties:
              pos:
                type: integer
                example: 5
                description: position
              p:
                type: integer
                example: 33
                description: points
              sg:
                type: integer
                example: 33
                description: scored_goals
              mg:
                type: integer
                example: 33
                description: missed_goals
              w:
                type: integer
                example: 33
                description: wins
              d:
                type: integer
                example: 33
                description: draws
              l:
                type: integer
                example: 33
                description: loses
              ts:
                type: string
                example: '599.5'
                description: total_score
          nullable: true
        league_id:
          type: integer
          example: 123
        loses:
          type: integer
          example: 3
        matches_played:
          type: integer
          example: 9
        missed_goals:
          type: integer
          example: 19
        next_opponent_id:
          type: integer
          example: 123
          nullable: true
          description: Team id of next opponent
        points:
          type: integer
          example: 43
        scored_goals:
          type: integer
          example: 53
        team_id:
          type: integer
          example: 153
        total_score:
          type: string
          example: '899.5'
        wins:
          type: integer
          example: 3
      required:
      - id
      - league_id
      - team_id
    season:
      type: object
      properties:
        id:
          type: integer
          example: 123
        end_year:
          type: integer
          example: 2024
        start_year:
          type: integer
          example: 2023
      required:
      - id
      - end_year
      - start_year
    team:
      type: object
      properties:
        id:
          type: integer
          example: 123
        budget:
          type: integer
          example: 260
        code:
          type: string
          example: ROS
        human_name:
          type: string
          example: Rossoneri
        league_id:
          type: integer
          example: 123
          nullable: true
        logo_path:
          type: string
          example: "/assets/path/team.png"
        players:
          type: array
          items:
            type: integer
            example: 13
          example:
          - '13'
          - '4323'
          - '954'
        user_id:
          type: integer
          example: 123
          nullable: true
      required:
      - id
    tournament:
      type: object
      properties:
        id:
          type: integer
          example: 123
        icon:
          type: string
          example: "\U0001F1EE\U0001F1F9"
          nullable: true
        logo:
          type: string
          example: "/assets/path/italy.png"
          nullable: true
        mantra_format:
          type: boolean
          example: true
          description: true for Mantra, false for national and eurocup leagues
        name:
          type: string
          example: Italy
        short_name:
          type: string
          example: Italy
          nullable: true
      required:
      - id
      - name
