export default {
  BASE_SCORE_MIN: 0,
  BASE_SCORE_MAX: 10,

  TOTAL_SCORE_MIN: 0,
  TOTAL_SCORE_MAX: 15,

  APPEARANCES_MIN: 0,
  APPEARANCES_MAX: 46,

  TEAMS_COUNT_MIN: 0,
  TEAMS_COUNT_MAX: 100,
};
