GMAIL_USERNAME: ""
GMAIL_PASSWORD: ""
MAILER_FROM: "noreply@yourdomain.com"
MAILGUN_SMTP_LOGIN: ""
MAILGUN_SMTP_PASSWORD: ""

TELEGRAM_DEV_BOT_TOKEN: ""
TELEGRAM_PROD_BOT_TOKEN: ""

DEV_HOST: "localhost"
