default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: mantra_development

test:
  <<: *default
  database: mantra_test

production:
  <<: *default
  database: mantra_production
  username: <%= Rails.application.credentials.dig(:production, :db, :username) %>
  password: <%= Rails.application.credentials.dig(:production, :db, :password) %>
  host: <%= Rails.application.credentials.dig(:production, :db, :host) %>
  port: 5432

staging:
  <<: *default
  database: mantra_staging
  username: <%= Rails.application.credentials.dig(:staging, :db, :username) %>
  password: <%= Rails.application.credentials.dig(:staging, :db, :password) %>
  host: <%= Rails.application.credentials.dig(:staging, :db, :host) %>
  port: 5432
