# config/secrets.yml
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot:  <%= ENV['TELEGRAM_PROD_BOT_TOKEN'] %>
    username: 'SomeBot'
    server: http://local.bot.api.server
    bots:
      mantra_prod: <%= ENV['TELEGRAM_PROD_BOT_TOKEN'] %>
    async: true

development:
  telegram:
    bot:  <%= ENV['TELEGRAM_DEV_BOT_TOKEN'] %>
    username: 'SomeBot'
    server: http://local.bot.api.server
    bots:
      mantra_prod: <%= ENV['TELEGRAM_DEV_BOT_TOKEN'] %>
    async: true

test:
  development:
  telegram:
    bot: 'token'
