import { Position } from "./Position";

export interface IRoundStat {
  id: number,
  assists: number,
  base_score: number | null,
  caught_penalty: number,
  cleansheet: boolean,
  club_id: number,
  club_logo_path: string | null,
  conceded_penalty: number,
  failed_penalty: number,
  goals: number,
  missed_penalty: number,
  missed_goals: number,
  own_goals: number,
  penalties_won: number,
  played_minutes: number,
  player_id: number,
  red_card: boolean,
  saves: number,
  scored_penalty: number,
  total_score: number | null,
  tournament_round_id: number,
  tournament_round_number: number,
  yellow_card: boolean,
}

export interface ISeasonTotal {
  assists: number,
  base_score: number,
  caught_penalty: number,
  cleansheet: number,
  conceded_penalty: number,
  failed_penalty: number,
  goals: number,
  missed_goals: number,
  missed_penalty: number,
  own_goals: number,
  penalties_won: number,
  played_matches: number,
  played_minutes: number,
  red_card: number,
  saves: number,
  scored_penalty: number,
  total_score: number,
  yellow_card: number,
}

export interface ISeasonStat {
  id: number,
  assists: number,
  base_score: number,
  caught_penalty: number,
  cleansheet: number,
  club_id: number,
  club_logo_path: string | null,
  conceded_penalty: number,
  failed_penalty: number,
  goals: number,
  missed_goals: number,
  missed_penalty: number,
  own_goals: number,
  penalties_won: number,
  played_matches: number,
  played_minutes: number,
  player_id: number,
  position_classic_arr: Position[],
  position_ital_arr: string[],
  position_price: number,
  red_card: number,
  saves: number,
  scored_penalty: number,
  season: { id: number, start_year: number, end_year: number } | null,
  season_id: number,
  sixties: number,
  total_score: number,
  tournament_id: number,
  yellow_card: number,
}

export interface IPlayerStats {
  id: number,
  current_season_stat: ISeasonTotal,
  current_season_stat_eurocup: ISeasonTotal,
  current_season_stat_national: ISeasonTotal,
  round_stats: IRoundStat[],
  round_stats_eurocup: IRoundStat[],
  round_stats_national: IRoundStat[],
  season_stats: ISeasonStat[],
}
