italy:
  - august
  - september
  - november
  - february
  - march
england:
  - august
  - september
  - november
  - february
  - march
germany:
  - august
  - september
  - november
  - february
  - march
france:
  - august
  - september
  - november
  - february
  - march
spain:
  - august
  - september
  - november
  - february
  - march
britain:
  - august
  - september
  - november
  - february
  - march
netherlands:
  - august
  - september
  - november
  - february
  - march
belgium:
  - july
  - september
  - november
  - february
  - march
portugal:
  - august
  - september
  - november
  - february
  - march
ukraine:
  - august
  - september
  - october
  - february
  - march
usa:
  - february
  - march
  - april
  - june
  - august
  - september
poland:
  - july
  - september
  - november
  - february
  - march
brazil:
  - january
  - february
  - march
  - april
  - july
  - august
  - september
  - october
turkey:
  - august
  - september
  - november
  - february
  - march
