serie_a:
  ATA: Atalanta
#  BEN: Benevento
  BOL: Bologna
#  BRE: Brescia
#  CAG: Cagliari
  CRE: Cremonese
#  CRO: Crotone
  EMP: Empoli
  FIO: Fiorentina
#  GEN: Genoa
  INT: Inter
  JUV: Juventus
  LAZ: Lazio
  LEC: Lecce
  MIL: Milan
  MNZ: Monza
  NAP: Napoli
#  PAR: Parma
  ROM: Roma
  SAL: Salernitana
  SAM: Sampdoria
  SAS: Sassuolo
#  SPA: SPAL
  SPE: Spezia
  TOR: Torino
  UDI: Udinese
#  VEN: Venezia
  VER: Verona
epl:
  ARS: Arsenal
  ASV: Aston Villa
  BRF: Brentford
  BRI: Brighton
  BUR: Burnley
  CHE: Chelsea
  CRY: Crystal Palace
  EVE: Everton
  LEI: Leicester
  LEE: Leeds
  LIV: Liverpool
  MCI: Manchester City
  MUT: Manchester United
  NEW: Newcastle
  NOR: Norwich
  SOU: Southampton
  TOT: Tottenham
  WAT: Watford
  WES: West Ham
  WOL: Wolverhampton
bundesliga:
#  ARM: Arminia
  AUG: Augsburg
  LEV: Bayer Leverkusen
  MUN: Bayern Munchen
  BOC: Bochum
  BVB: Borussia Dortmund
  BMG: Borussia Mbach
  EIN: Eintracht
  FRE: Freiburg
#  GRF: Greuther Furth
  HER: Hertha
  HOF: Hoffenheim
  KOL: Koln
  MAI: Mainz 05
  RBL: RB Leipzig
  S04: Schalke 04
  STU: Stuttgart
  UNI: Union Berlin
  WER: Werder Bremen
  WLF: Wolfsburg
laliga:
  ALM: Almeria
  ATB: Athletic Bilbao
  ATM: Atletico Madrid
  BAR: Barcelona
  BET: Real Betis
  CAD: Cadiz
  CVG: Celta Vigo
#  ALA: Deportivo Alaves
  ELC: Elche
  ESP: Espanyol
  GET: Getafe
  GIR: Girona
#  GRA: Granada
#  LUD: Levante
  MAL: Mallorca
  OSA: Osasuna
  RVA: Rayo Vallecano
  RMA: Real Madrid
  SOC: Real Sociedad
  VLD: Real Valladolid
  SEV: Sevilla
  VAL: Valencia
  VIL: Villarreal
ligue_1:
  AJC: Ajaccio
  ANG: Angers
  AUX: Auxerre
#  BOR: Bordeaux
  BRS: Brest
  CLE: Clermont Foot
  LEN: Lens
  LIL: Lille
  LOR: Lorient
  LYO: Lyon
  MAR: Marseille
#  MET: Metz
  MON: Monaco
  MPL: Montpellier
  NAN: Nantes
  NIC: Nice
  PSG: PSG
  REI: Reims
  REN: Rennes
#  SEN: Saint-Etienne
  STR: Strasbourg
  TOU: Toulouse
  TRO: Troyes
championship:
  BIR: Birmingham City
  BLB: Blackburn Rovers
  BLP: Blackpool
  BRC: Bristol City
  BOU: Bournemouth
  CAR: Cardiff City
  COV: Coventry City
  FUL: Fulham
  HUD: Huddersfield Town
  HUL: Hull City
  LUT: Luton Town
  MID: Middlesbrough
  MLW: Millwall
  NFO: Nottingham Forest
  PRE: Preston North End
  QPR: Queens Park Rangers
  REA: Reading
  ROT: Rotherham United
  SHU: Sheffield United
  STO: Stoke City
  SUN: Sunderland
  SWA: Swansea City
  WBA: West Bromwich
  WIG: Wigan Athletic
jupiler:
  AND: Anderlecht
  BRU: Brugge
  CBG: Cercle Brugge
  CHR: Charleroi
  EPN: Eupen
  GNK: Genk
  GNT: Gent
  KRT: Kortrijk
  LVN: Leuven
  MLN: Mechelen
  OST: Oostende
  ROY: Royal Antwerp
  SRN: Seraing
  STT: Sint-Truiden
  STD: Standard Liege
  USG: Union SG
  WST: Westerlo
  ZWR: Zulte Waregem
liga_portugal:
  ARC: Arouca
  BNF: Benfica
  BVS: Boavista
  BRG: Braga
  CSP: Casa Pia
  CHV: Chaves
  EST: Estoril
  FML: Famalicao
  GLV: Gil Vicente
  MRT: Maritimo
  PCF: Pa—Åos Ferreira
  PRT: Portimonense
  FCP: Porto
  RAV: Rio Ave
  SCL: Santa Clara
  SCP: Sporting
  VTG: Vitoria Guimaraes
  VZL: Vizela
eredivisie:
  AJA: Ajax
  AZA: AZ Alkmaar
  CMB: Cambuur
  EMN: Emmen
  EXL: Excelsior
  FND: Feyenoord
  FRS: Fortuna Sittard
  GAE: Go Ahead Eagles
  GRN: Groningen
  HRN: Heerenveen
  NEC: NEC
  PSV: PSV
  RKC: RKC Waalwijk
  SPR: Sparta
  TWT: Twente
  UTR: Utrecht
  VTS: Vitesse
  VLN: Volendam
champions_league:
#  BES: Besiktas
  CEL: Celtic
  COP: Copenhagen
  DZG: Dinamo Zagreb
#  DYN: Dynamo Kyiv
  MHF: Maccabi Haifa
#  MFF: Malmo
  RAN: Rangers
  RBS: Salzburg
  SHD: Shakhtar Donetsk
#  SHE: Sheriff
  VPL: Viktoria Plzen
#  YOU: Young Boys
#  ZEN: Zenit
