serie_a:
  ATA: Atalanta
  BEN: Benevento
  BOL: Bologna
  CAG: Cagliari
  CRO: Crotone
  FIO: Fiorentina
  GEN: Genoa
  INT: Inter
  JUV: Juventus
  LAZ: Lazio
  MIL: Milan
  NAP: Napoli
  PAR: Parma
  ROM: Roma
  SAM: Sampdoria
  SAS: Sassuolo
  SPE: Spezia
  TOR: Torino
  UDI: Udinese
  VER: Verona
epl:
  ARS: Arsenal
  ASV: Aston Villa
  BRI: Brighton
  BUR: Burnley
  CHE: Chelsea
  CRY: Crystal Palace
  EVE: Everton
  FUL: Fulham
  LEI: Leicester
  LEE: Leeds
  LIV: Liverpool
  MCI: Manchester City
  MUT: Manchester United
  NEW: Newcastle
  SHU: Sheffield United
  SOU: Southampton
  TOT: Tottenham
  WBA: West Bromwich
  WES: West Ham
  WOL: Wolverhampton
bundesliga:
  ARM: Arminia
  AUG: Augsburg
  LEV: Bayer Leverkusen
  MUN: Bayern Munchen
  BVB: Borussia Dortmund
  BMG: Borussia Mbach
  EIN: Eintracht
  FRE: Freiburg
  HER: Hertha
  HOF: Hoffenheim
  KOL: Koln
  MAI: Mainz 05
  RBL: RB Leipzig
  S04: Schalke 04
  STU: Stuttgart
  UNI: Union Berlin
  WER: Werder Bremen
  WLF: Wolfsburg
