serie_a:
  ATA: Atalanta
  BOL: Bologna
  CAG: Cagliari
  EMP: Empoli
  FIO: Fiorentina
  GEN: Genoa
  INT: Inter
  JUV: Juventus
  LAZ: Lazio
  MIL: Milan
  NAP: Napoli
  ROM: Roma
  SAL: Salernitana
  SAM: Sampdoria
  SAS: Sassuolo
  SPE: Spezia
  TOR: Torino
  UDI: Udinese
  VEN: Venezia
  VER: Verona
epl:
  ARS: Arsenal
  ASV: Aston Villa
  BRF: Brentford
  BRI: Brighton
  BUR: Burnley
  CHE: Chelsea
  CRY: Crystal Palace
  EVE: Everton
  LEI: Leicester
  LEE: Leeds
  LIV: Liverpool
  MCI: Manchester City
  MUT: Manchester United
  NEW: Newcastle
  NOR: Norwich
  SOU: Southampton
  TOT: Tottenham
  WAT: Watford
  WES: West Ham
  WOL: Wolverhampton
bundesliga:
  ARM: Arminia
  AUG: Augsburg
  BOC: Bochum
  LEV: Bayer Leverkusen
  MUN: Bayern Munchen
  BVB: Borussia Dortmund
  BMG: Borussia Mbach
  EIN: Eintracht
  FRE: Freiburg
  GRF: Greuther Furth
  HER: Hertha
  HOF: Hoffenheim
  KOL: Koln
  MAI: Mainz 05
  RBL: RB Leipzig
  STU: Stuttgart
  UNI: Union Berlin
  WLF: Wolfsburg
laliga:
  ATB: Athletic Bilbao
  ATM: Atletico Madrid
  BAR: Barcelona
  BET: Real Betis
  CAD: Cadiz
  CEL: Celta Vigo
  ALA: Deportivo Alaves
  ELC: Elche
  ESP: Espanyol
  GET: Getafe
  GIR: Girona
  GRA: Granada
  LUD: Levante
  MAL: Mallorca
  OSA: Osasuna
  RVA: Rayo Vallecano
  RMA: Real Madrid
  SOC: Real Sociedad
  SEV: Sevilla
  VAL: Valencia
  VIL: Villarreal
ligue_1:
  ANG: Angers
  BOR: Bordeaux
  BRS: Brest
  CLE: Clermont Foot
  LEN: Lens
  LIL: Lille
  LOR: Lorient
  LYO: Lyon
  MAR: Marseille
  MET: Metz
  MON: Monaco
  MPL: Montpellier
  NAN: Nantes
  NIC: Nice
  PSG: PSG
  REI: Reims
  REN: Rennes
  SEN: Saint-Etienne
  STR: Strasbourg
  TRO: Troyes
championship:
  BIR: Birmingham City
  BLB: Blackburn Rovers
  BLP: Blackpool
  BRC: Bristol City
  BOU: Bournemouth
  CAR: Cardiff City
  COV: Coventry City
  FUL: Fulham
  HUD: Huddersfield Town
  HUL: Hull City
  LUT: Luton Town
  MID: Middlesbrough
  MLW: Millwall
  NFO: Nottingham Forest
  PRE: Preston North End
  QPR: Queens Park Rangers
  REA: Reading
  ROT: Rotherham United
  SHU: Sheffield United
  STO: Stoke City
  SUN: Sunderland
  SWA: Swansea City
  WBA: West Bromwich
  WIG: Wigan Athletic
champions_league:
  BRU: Brugge
  PSG: PSG
  MCI: Manchester City
  RBL: RB Leipzig
  MIL: Milan
  ATM: Atletico Madrid
  FCP: Porto
  LIV: Liverpool
  AJA: Ajax
  BES: Besiktas
  BVB: Borussia Dortmund
  SCP: Sporting
  SHE: Sheriff
  INT: Inter
  RMA: Real Madrid
  SHD: Shakhtar Donetsk
  BAR: Barcelona
  MUN: Bayern Munchen
  BNF: Benfica
  DYN: Dynamo Kyiv
  ATA: Atalanta
  MUT: Manchester United
  VIL: Villarreal
  YOU: Young Boys
  LIL: Lille
  RBS: Salzburg
  SEV: Sevilla
  WLF: Wolfsburg
  CHE: Chelsea
  JUV: Juventus
  MFF: Malmo
  ZEN: Zenit
