serie_a:
  ATA: Atalanta
#  BEN: Benevento
  BOL: Bologna
#  BRE: Brescia
  CAG: Cagliari
#  CRE: Cremonese
#  CRO: Crotone
  EMP: Empoli
  FIO: Fiorentina
  FRO: Frosinone
  GEN: Genoa
  INT: Inter
  JUV: Juventus
  LAZ: Lazio
  LEC: Lecce
  MIL: Milan
  MNZ: Monza
  NAP: Napoli
#  PAR: Parma
  ROM: Roma
  SAL: Salernitana
#  SAM: Sampdoria
  SAS: Sassuolo
#  SPA: SPAL
#  SPE: Spezia
  TOR: Torino
  UDI: Udinese
#  VEN: Venezia
  VER: Verona
epl:
  ARS: Arsenal
  ASV: Aston Villa
  BOU: Bournemouth
  BRF: Brentford
  BRI: Brighton
  BUR: Burnley
  CHE: Chelsea
  CRY: Crystal Palace
  EVE: Everton
  FUL: Fulham
  LIV: Liverpool
  LUT: Luton Town
  MCI: Manchester City
  MUT: Manchester United
  NEW: Newcastle
  NFO: Nottingham Forest
  SHU: Sheffield United
  TOT: Tottenham
  WES: West Ham
  WOL: Wolverhampton
bundesliga:
#  ARM: Arminia
  AUG: Augsburg
  LEV: Bayer Leverkusen
  MUN: Bayern Munchen
  BOC: Bochum
  BVB: Borussia Dortmund
  BMG: Borussia Mbach
  DAR: Darmstadt
  EIN: Eintracht
  FRE: Freiburg
#  GRF: Greuther Furth
  HEI: Heidenheim
#  HER: Hertha
  HOF: Hoffenheim
  KOL: Koln
  MAI: Mainz 05
  RBL: RB Leipzig
#  S04: Schalke 04
  STU: Stuttgart
  UNI: Union Berlin
  WER: Werder Bremen
  WLF: Wolfsburg
laliga:
  ALM: Almeria
  ATB: Athletic Bilbao
  ATM: Atletico Madrid
  BAR: Barcelona
  BET: Real Betis
  CAD: Cadiz
  CVG: Celta Vigo
  ALA: Deportivo Alaves
#  ELC: Elche
#  ESP: Espanyol
  GET: Getafe
  GIR: Girona
  GRA: Granada
#  LUD: Levante
  LPA: Las Palmas
  MAL: Mallorca
  OSA: Osasuna
  RVA: Rayo Vallecano
  RMA: Real Madrid
  SOC: Real Sociedad
#  VLD: Real Valladolid
  SEV: Sevilla
  VAL: Valencia
  VIL: Villarreal
ligue_1:
#  AJC: Ajaccio
#  ANG: Angers
#  AUX: Auxerre
#  BOR: Bordeaux
  BRS: Brest
  CLE: Clermont Foot
  HAV: Havre
  LEN: Lens
  LIL: Lille
  LOR: Lorient
  LYO: Lyon
  MAR: Marseille
  MET: Metz
  MON: Monaco
  MPL: Montpellier
  NAN: Nantes
  NIC: Nice
  PSG: PSG
  REI: Reims
  REN: Rennes
#  SEN: Saint-Etienne
  STR: Strasbourg
  TOU: Toulouse
#  TRO: Troyes
championship:
  BIR: Birmingham City
  BLB: Blackburn Rovers
#  BLP: Blackpool
  BRC: Bristol City
  CAR: Cardiff City
  COV: Coventry City
  HUD: Huddersfield Town
  HUL: Hull City
  IPS: Ipswich
  LEI: Leicester
  LEE: Leeds
  MID: Middlesbrough
  MLW: Millwall
  NOR: Norwich
  PLY: Plymouth
  PRE: Preston North End
  QPR: Queens Park Rangers
#  REA: Reading
  ROT: Rotherham United
  SHW: Sheffield Wednesday
  SOU: Southampton
  STO: Stoke City
  SUN: Sunderland
  SWA: Swansea City
  WAT: Watford
  WBA: West Bromwich
#  WIG: Wigan Athletic
jupiler:
  AND: Anderlecht
  BRU: Brugge
  CBG: Cercle Brugge
  CHR: Charleroi
  EPN: Eupen
  GNK: Genk
  GNT: Gent
  KRT: Kortrijk
  LVN: Leuven
  MLN: Mechelen
  MOL: Molenbeek
#  OST: Oostende
  ROY: Royal Antwerp
#  SRN: Seraing
  STT: Sint-Truiden
  STD: Standard Liege
  USG: Union SG
  WST: Westerlo
#  ZWR: Zulte Waregem
liga_portugal:
  ARC: Arouca
  BNF: Benfica
  BVS: Boavista
  BRG: Braga
  CSP: Casa Pia
  CHV: Chaves
  EST: Estoril
  ESA: Estrela
  FML: Famalicao
  FAR: Farense
  GLV: Gil Vicente
#  MRT: Maritimo
  MOR: Moreirense
#  PCF: Pa—Åos Ferreira
  PRT: Portimonense
  FCP: Porto
  RAV: Rio Ave
#  SCL: Santa Clara
  SCP: Sporting
  VTG: Vitoria Guimaraes
  VZL: Vizela
eredivisie:
  AJA: Ajax
  ALC: Almere City
  AZA: AZ Alkmaar
#  CMB: Cambuur
#  EMN: Emmen
  EXL: Excelsior
  FND: Feyenoord
  FRS: Fortuna Sittard
  GAE: Go Ahead Eagles
#  GRN: Groningen
  HRC: Heracles
  HRN: Heerenveen
  NEC: NEC
  PSV: PSV
  RKC: RKC Waalwijk
  SPR: Sparta
  TWT: Twente
  UTR: Utrecht
  VTS: Vitesse
  VLN: Volendam
  ZWO: Zwolle
champions_league:
#  BES: Besiktas
  CEL: Celtic
  COP: Copenhagen
  DZG: Dinamo Zagreb
#  DYN: Dynamo Kyiv
  MHF: Maccabi Haifa
#  MFF: Malmo
  RAN: Rangers
  RBS: Salzburg
  SHD: Shakhtar Donetsk
#  SHE: Sheriff
  VPL: Viktoria Plzen
#  YOU: Young Boys
#  ZEN: Zenit
