clubs:
  - Atalanta
  - Bologna
  - Cagliari
  - Chievo
  - Empoli
  - Fiorentina
  - Frosinone
  - Genoa
  - Inter
  - Juventus
  - Lazio
  - Milan
  - Napoli
  - Parma
  - Roma
  - Sampdoria
  - Sassuolo
  - SPAL
  - Torino
  - Udinese
