clubs:
  - Atalanta
  - Bologna
  - Brescia
  - Cagliari
  - Fiorentina
  - Genoa
  - Inter
  - Juventus
  - Lazio
  - Lecce
  - Milan
  - Napoli
  - Parma
  - Roma
  - Sampdoria
  - Sassuolo
  - SPAL
  - Torino
  - Udinese
  - Verona
