euro:
  al: Albania
  dk: Denmark
  fi: Finland
  gb-wls: Wales
  ge: Georgia
  hu: Hungary
  it: Italy
  mk: North Macedonia
  pl: Poland
  ro: Romania
  rs: Serbia
  ru: Russia
  si: Slovenia
  sk: Slovakia
  ua: Ukraine
  xx: Undefined
afcon:
  ao: Angola
  bf: Burkina Faso
  bj: Benin
  bw: Botswana
  cm: Cameroon
  ga: Gabon
  gq: Equatorial Guinea
  km: Comoros
  ml: Mali
  mz: Mozambique
  ng: Nigeria
  sd: Sudan
  tz: Tanzania
  ug: Uganda
  zm: Zambia
  zw: Zimbabwe
world_cup:
  ar: Argentina
  at: Austria
  au: Australia
  ba: Bosnia and Herzegovina
  be: Belgium
  br: Brazil
  ca: Canada
  cd: DR Congo
  ch: Switzerland
  ci: Ivory Coast
  co: Colombia
  cv: Cabo Verde
  cw: Curacao
  cz: Czechia
  de: Germany
  dz: Algeria
  ec: Ecuador
  eg: Egypt
  es: Spain
  fr: France
  gb-eng: England
  gb-sct: Scotland
  gh: Ghana
  hr: Croatia
  ht: Haiti
  iq: Iraq
  ir: Iran
  jo: Jordan
  jp: Japan
  kr: South Korea
  ma: Morocco
  mx: Mexico
  nl: Netherlands
  no: Norway
  nz: New Zealand
  pa: Panama
  pt: Portugal
  py: Paraguay
  qa: Qatar
  sa: Saudi Arabia
  se: Sweden
  sn: Senegal
  tn: Tunisia
  tr: Turkiye
  us: USA
  uy: Uruguay
  uz: Uzbekistan
  za: South Africa
