euro:
  al: Albania
  at: Austria
  be: Belgium
  ch: Switzerland
  cz: Czechia
  de: Germany
  dk: Denmark
  es: Spain
  fi: Finland
  fr: France
  gb-eng: England
  gb-sct: Scotland
  gb-wls: Wales
  ge: Georgia
  hr: Croatia
  hu: Hungary
  it: Italy
  mk: North Macedonia
  nl: Netherlands
  pl: Poland
  pt: Portugal
  ro: Romania
  rs: Serbia
  ru: Russia
  se: Sweden
  si: Slovenia
  sk: Slovakia
  tr: Turkiye
  ua: Ukraine
  xx: Undefined
world_cup:
  ec: Ecuador
  qa: Qatar
  sn: Senegal
  ir: Iran
  us: USA
  ar: Argentina
  mx: Mexico
  sa: Saudi Arabia
  au: Australia
  tn: Tunisia
  cr: Costa Rica
  jp: Japan
  ca: Canada
  ma: Morocco
  br: Brazil
  cm: Cameroon
  gh: Ghana
  kr: South Korea
  uy: Uruguay