euro:
  it: Italy
  ch: Switzerland
  tr: Turkey
  gb-wls: Wales
  be: Belgium
  dk: Denmark
  fi: Finland
  ru: Russia
  at: Austria
  nl: Netherlands
  mk: North Macedonia
  ua: Ukraine
  hr: Croatia
  cz: Czech Republic
  gb-eng: England
  gb-sct: Scotland
  pl: Poland
  sk: Slovakia
  es: Spain
  se: Sweden
  fr: France
  de: Germany
  hu: Hungary
  pt: Portugal
  xx: Undefined
