euro:
  it: Italy
  ch: Switzerland
  tr: Turkey
  gb-wls: Wales
  be: Belgium
  dk: Denmark
  fi: Finland
  ru: Russia
  at: Austria
  nl: Netherlands
  mk: North Macedonia
  ua: Ukraine
  hr: Croatia
  cz: Czech Republic
  gb-eng: England
  gb-sct: Scotland
  pl: Poland
  sk: Slovakia
  es: Spain
  se: Sweden
  fr: France
  de: Germany
  hu: Hungary
  pt: Portugal
  xx: Undefined
world_cup:
  ec: Ecuador
  qa: Qatar
  sn: Senegal
  ir: Iran
  us: USA
  ar: Argentina
  mx: Mexico
  sa: Saudi Arabia
  au: Australia
  tn: Tunisia
  cr: Costa Rica
  jp: Japan
  ca: Canada
  ma: Morocco
  br: Brazil
  cm: Cameroon
  rs: Serbia
  gh: Ghana
  kr: South Korea
  uy: Uruguay