3-4-3:
  1:
    - Por
  2:
    - Dc
  3:
    - Dc
  4:
    - Dc
  5:
    - E
  6:
    - E
  7:
    - M
    - C
  8:
    - C
  9:
    - W
    - A
  10:
    - W
    - A
  11:
    - A
    - Pc
3-4-1-2:
  1:
    - Por
  2:
    - Dc
  3:
    - Dc
  4:
    - Dc
  5:
    - E
  6:
    - E
  7:
    - M
    - C
  8:
    - C
  9:
    - T
  10:
    - A
    - Pc
  11:
    - Pc
3-4-2-1:
  1:
    - Por
  2:
    - Dc
  3:
    - Dc
  4:
    - Dc
  5:
    - E
  6:
    - M
  7:
    - M
    - C
  8:
    - E
    - W
  9:
    - T
  10:
    - T
    - A
  11:
    - A
    - Pc
3-5-2:
  1:
    - Por
  2:
    - Dc
  3:
    - Dc
  4:
    - Dc
  5:
    - E
  6:
    - M
  7:
    - M
    - C
  8:
    - C
  9:
    - E
    - W
  10:
    - A
    - Pc
  11:
    - Pc
3-5-1-1:
  1:
    - Por
  2:
    - Dc
  3:
    - Dc
  4:
    - Dc
  5:
    - M
  6:
    - M
  7:
    - C
  8:
    - E
    - W
  9:
    - E
    - W
  10:
    - T
    - A
  11:
    - A
    - Pc
4-3-3:
  1:
    - Por
  2:
    - Dd
  3:
    - Dc
  4:
    - Dc
  5:
    - Ds
  6:
    - M
  7:
    - M
    - C
  8:
    - C
  9:
    - W
    - A
  10:
    - W
    - A
  11:
    - A
    - Pc
4-3-1-2:
  1:
    - Por
  2:
    - Dd
  3:
    - Dc
  4:
    - Dc
  5:
    - Ds
  6:
    - M
  7:
    - M
    - C
  8:
    - C
  9:
    - T
  10:
    - A
    - Pc
  11:
    - Pc
4-4-2:
  1:
    - Por
  2:
    - Dd
  3:
    - Dc
  4:
    - Dc
  5:
    - Ds
  6:
    - E
  7:
    - M
    - C
  8:
    - C
  9:
    - E
    - W
  10:
    - A
    - Pc
  11:
    - Pc
4-1-4-1:
  1:
    - Por
  2:
    - Dd
  3:
    - Dc
  4:
    - Dc
  5:
    - Ds
  6:
    - M
  7:
    - C
    - T
  8:
    - C
    - T
  9:
    - W
  10:
    - W
  11:
    - A
    - Pc
4-4-1-1:
  1:
    - Por
  2:
    - Dd
  3:
    - Dc
  4:
    - Dc
  5:
    - Ds
  6:
    - M
  7:
    - C
  8:
    - E
    - W
  9:
    - E
    - W
  10:
    - T
    - A
  11:
    - A
    - Pc
4-2-3-1:
  1:
    - Por
  2:
    - Dd
  3:
    - Dc
  4:
    - Dc
  5:
    - Ds
  6:
    - M
  7:
    - M
    - C
  8:
    - T
  9:
    - T
    - W
  10:
    - W
    - A
  11:
    - A
    - Pc
4-3-2-1:
  1:
    - Por
  2:
    - Dd
  3:
    - Dc
  4:
    - Dc
  5:
    - Ds
  6:
    - M
  7:
    - M
    - C
  8:
    - C
  9:
    - T
    - A
  10:
    - T
    - A
  11:
    - A
    - Pc
