3-4-3:
  1:
    - Por
  2:
    - Dc
  3:
    - Dc
  4:
    - Dc
  5:
    - E
  6:
    - M
    - C
  7:
    - M
    - C
  8:
    - E
  9:
    - W
    - A
  10:
    - A
    - Pc
  11:
    - W
    - A
4-3-3:
  1:
    - Por
  2:
    - Dd
  3:
    - Dc
  4:
    - Dc
  5:
    - Ds
  6:
    - M
    - C
  7:
    - M
  8:
    - M
    - C
  9:
    - W
    - A
  10:
    - A
    - Pc
  11:
    - W
    - A
