serie_a:
  name: 'Serie A'
  eurocup: false
epl:
  name: 'Premier League'
  eurocup: false
bundesliga:
  name: 'Bundesliga'
  eurocup: false
ligue_1:
  name: 'Ligue 1'
  eurocup: false
laliga:
  name: 'LaLiga'
  eurocup: false
upl:
  name: 'Ukrainian Premier League'
  eurocup: false
euro:
  name: 'Euro 2020'
  eurocup: false
champions_league:
  name: 'Champions League'
  eurocup: true
