italy:
  name: 'Italy'
  eurocup: false
england:
  name: 'England'
  eurocup: false
germany:
  name: 'Germany'
  eurocup: false
france:
  name: 'France'
  eurocup: false
spain:
  name: 'Spain'
  eurocup: false
ukraine:
  name: 'Ukraine'
  eurocup: false
euro:
  name: 'Euro 2024'
  eurocup: false
europe:
  name: 'Europe CL'
  eurocup: true
