# frozen_string_literal: true

class Position < ApplicationRecord
  has_many :player_positions, dependent: :destroy
  has_many :players, through: :player_positions

  validates :name, presence: true
  validates :name, uniqueness: true

  PORTIERE = 'Por'
  ESTERNO  = 'E'
  DIFENSORE_SINISTRO = 'Ds'
  DIFENSORE_DESTRO   = 'Dd'
  DIFENSORE_CENTRALE = 'Dc'
  MEDIANO = 'M'
  CENTROCAMPISTA = 'C'
  ALA = 'W'
  TREQUARTSITA = 'T'
  ATTACCANTE = 'A'
  PUNTA = 'Pc'

  S_MALUS = 1.5
  M_MALUS = 3.0
  L_MALUS = 4.5

  CLEANSHEET_ZONE = [PORTIERE, DIFENSORE_CENTRALE, DIFENSORE_SINISTRO, DIFENSORE_DESTRO, MEDIANO, ESTERNO].freeze
  D_CLEANSHEET_ZONE = [DIFENSORE_CENTRALE, DIFENSORE_SINISTRO, DIFENSORE_DESTRO].freeze
  E_M_CLEANSHEET_ZONE = [MEDIANO, ESTERNO].freeze

  DEFENCE = [DIFENSORE_CENTRALE, DIFENSORE_SINISTRO, DIFENSORE_DESTRO].freeze

  FORWARDS = [ATTACCANTE, PUNTA].freeze

  MANTRA = [
    PORTIERE,
    ESTERNO,
    DIFENSORE_SINISTRO,
    DIFENSORE_DESTRO,
    DIFENSORE_CENTRALE,
    MEDIANO,
    CENTROCAMPISTA,
    ALA,
    TREQUARTSITA,
    ATTACCANTE,
    PUNTA
  ].freeze

  # Position in lineup => Native Positions
  DEPENDENCY = {
    PORTIERE => [PORTIERE],
    DIFENSORE_SINISTRO => [DIFENSORE_SINISTRO, DIFENSORE_DESTRO, DIFENSORE_CENTRALE, ESTERNO],
    DIFENSORE_DESTRO => [DIFENSORE_DESTRO, DIFENSORE_SINISTRO, DIFENSORE_CENTRALE, ESTERNO],
    DIFENSORE_CENTRALE => [DIFENSORE_CENTRALE, DIFENSORE_DESTRO, DIFENSORE_SINISTRO, MEDIANO],
    ESTERNO => [ESTERNO, DIFENSORE_DESTRO, DIFENSORE_SINISTRO, ALA],
    MEDIANO => [MEDIANO, CENTROCAMPISTA, DIFENSORE_CENTRALE],
    CENTROCAMPISTA => [CENTROCAMPISTA, MEDIANO, TREQUARTSITA],
    ALA => [ALA, ESTERNO, TREQUARTSITA, ATTACCANTE],
    TREQUARTSITA => [TREQUARTSITA, CENTROCAMPISTA, ALA, ATTACCANTE],
    ATTACCANTE => [ATTACCANTE, PUNTA, TREQUARTSITA, ALA],
    PUNTA => [PUNTA, ATTACCANTE]
  }.freeze

  # Position in lineup => Native Position => Malus size
  MALUS = {
    DIFENSORE_SINISTRO => { DIFENSORE_DESTRO => S_MALUS,
                            DIFENSORE_CENTRALE => S_MALUS,
                            ESTERNO => M_MALUS },
    DIFENSORE_DESTRO => { DIFENSORE_SINISTRO => S_MALUS,
                          DIFENSORE_CENTRALE => S_MALUS,
                          ESTERNO => M_MALUS },
    DIFENSORE_CENTRALE => { DIFENSORE_DESTRO => S_MALUS,
                            DIFENSORE_SINISTRO => S_MALUS,
                            MEDIANO => M_MALUS },
    ESTERNO => { DIFENSORE_DESTRO => M_MALUS,
                 DIFENSORE_SINISTRO => M_MALUS,
                 ALA => M_MALUS },
    MEDIANO => { CENTROCAMPISTA => S_MALUS,
                 DIFENSORE_CENTRALE => M_MALUS },
    CENTROCAMPISTA => { MEDIANO => S_MALUS,
                        TREQUARTSITA => M_MALUS },
    ALA => { TREQUARTSITA => S_MALUS,
             ESTERNO => M_MALUS,
             ATTACCANTE => M_MALUS },
    TREQUARTSITA => { ALA => S_MALUS,
                      CENTROCAMPISTA => M_MALUS,
                      ATTACCANTE => M_MALUS },
    ATTACCANTE => { PUNTA => S_MALUS,
                    ALA => M_MALUS,
                    TREQUARTSITA => M_MALUS },
    PUNTA => { ATTACCANTE => S_MALUS }
  }.freeze
end
